export const supabaseUrl = 'https://ergflyvuetfsmeakixbd.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZ2ZseXZ1ZXRmc21lYWtpeGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4Mzg2MjEsImV4cCI6MjA4NjQxNDYyMX0.iZ8bPc3DUInatBseTScJXzARqwG1VSCAFru5iphbBFU';
